version: '3'

services:
  app:
    build: .
    container_name: go-app
    ports:
      - "3000:3000"

  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"